FROM continuumio/miniconda3:4.3.27


# Copies Code and data to the Docker container

COPY /pySpark/main.py /pySpark/main.py

COPY players_21.csv players_21.csv 

# Installs dependencies
RUN conda install -c conda-forge pyspark

RUN conda install -c conda-forge notebook

CMD jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
