FROM confluentinc/cp-kafka-connect-base:6.1.0

#installs the twitter connector
RUN confluent-hub install jcustenborder/kafka-connect-twitter:0.3.33 --no-prompt

#installs the datagen connector
RUN confluent-hub install confluentinc/kafka-connect-datagen:0.4.0 --no-prompt

#installs the elastichsearch connector
RUN confluent-hub install confluentinc/kafka-connect-elasticsearch:5.4.0 --no-prompt


#Create Topics [tweets,countByName,countByLang]
RUN kafka-topics --create \
  --bootstrap-server localhost:9092 \
  --replication-factor 1 \
  --partitions 1 \
  --topic tweets

RUN kafka-topics --create \
  --bootstrap-server localhost:9092 \
  --replication-factor 1 \
  --partitions 1 \
  --topic countByName

RUN kafka-topics --create \
  --bootstrap-server localhost:9092 \
  --replication-factor 1 \
  --partitions 1 \
  --topic countByLang

#Upload Twitter Connector Configuration

#Upload Elasticsearch Connector Configuration